#!/usr/bin/env python3
"""Historiador Setup Wizard — interactive CLI to configure the app on first run.

Usage:
    python scripts/setup.py          # interactive wizard
    python scripts/setup.py --quick  # use all defaults, write .env silently
"""

import base64
import os
import sys
from datetime import datetime
from pathlib import Path

# Project root is one level above scripts/
PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = PROJECT_ROOT / ".env"

# ── Defaults ────────────────────────────────────────────────────────────────

DEFAULTS = {
    "LLM_API_KEY": "",
    "LLM_BASE_URL": "https://api.nan.builders/v1",
    "LLM_MODEL": "deepseek-v4-flash",
    "SEARCH_PROVIDER": "duckduckgo",
    "TAVILY_API_KEY": "",
    "SERPAPI_API_KEY": "",
    "HERMES_PATH": "hermes",
    "DATABASE_URL": "sqlite+aiosqlite:///./historiador.db",
    "VAPID_PUBLIC_KEY": "",
    "VAPID_PRIVATE_KEY": "",
    "VAPID_CLAIM_EMAIL": "admin@historiador.app",
    "DEFAULT_NUM_HISTORIES": "2",
    "DEFAULT_NUM_RESEARCH_AGENTS": "3",
    "MAX_SCOPING_ROUNDS": "5",
    "MAX_QUERIES_PER_AGENT": "3",
    "MAX_PAGES_PER_QUERY": "3",
    "MAX_CHARS_PER_PAGE": "10000",
    "MAX_RESEARCH_TOKENS": "8000",
    "RESEARCH_TIMEOUT_SECONDS": "60",
}

SEARCH_PROVIDERS = {
    "1": ("duckduckgo", "Free, no API key (recommended)"),
    "2": ("direct", "Free, scrapes DuckDuckGo HTML directly"),
    "3": ("hermes", "Uses Hermes CLI subagent with web toolset"),
    "4": ("tavily", "Tavily Search API (requires TAVILY_API_KEY)"),
    "5": ("serpapi", "SerpAPI Google results (requires SERPAPI_API_KEY)"),
    "6": ("mock", "No-op fallback — Wikipedia links only"),
}

LLM_MODELS = [
    "deepseek-v4-flash",
    "claude-sonnet-4",
    "gpt-4o",
    "gpt-4o-mini",
    "gemini-2.5-pro",
    "custom",
]


# ── Helpers ─────────────────────────────────────────────────────────────────


def banner():
    print()
    print("╔══════════════════════════════════════════════════════════╗")
    print("║               Historiador Setup Wizard                  ║")
    print("║         Multi-Agent History Generator                   ║")
    print("╚══════════════════════════════════════════════════════════╝")
    print()


def section(title: str):
    print()
    print(f"{'─' * 50}")
    print(f"  {title}")
    print(f"{'─' * 50}")


def prompt_input(label: str, default: str = "") -> str:
    val = input(f"{label} [{default}]: ").strip() if default else input(f"{label}: ").strip()
    return val or default


def prompt_choice(label: str, options: dict[str, tuple[str, str]]) -> str:
    print()
    for key, (value, desc) in options.items():
        print(f"  [{key}] {desc}")
    print()
    while True:
        choice = input(f"{label} (1-{len(options)}): ").strip()
        if choice in options:
            return options[choice][0]


def prompt_bool(label: str, default: bool = False) -> bool:
    d = "Y/n" if default else "y/N"
    ans = input(f"{label} [{d}]: ").strip().lower()
    if not ans:
        return default
    return ans in ("y", "yes", "true")


# ── Environment file writer ─────────────────────────────────────────────────


def write_env(config: dict):
    lines = [
        "# Historiador Configuration",
        f"# Generated by setup wizard on {datetime.now():%Y-%m-%d %H:%M}",
        "",
    ]

    # LLM
    lines.append("# ── LLM Provider ───────────────────────────────────────")
    lines.append(f"LLM_API_KEY={config['LLM_API_KEY']}")
    lines.append(f"LLM_BASE_URL={config['LLM_BASE_URL']}")
    lines.append(f"LLM_MODEL={config['LLM_MODEL']}")
    lines.append("")

    # Search
    lines.append("# ── Search Provider ────────────────────────────────────")
    lines.append(f"SEARCH_PROVIDER={config['SEARCH_PROVIDER']}")
    lines.append(f"TAVILY_API_KEY={config['TAVILY_API_KEY']}")
    lines.append(f"SERPAPI_API_KEY={config['SERPAPI_API_KEY']}")
    lines.append(f"HERMES_PATH={config['HERMES_PATH']}")
    lines.append("")

    # Database
    lines.append("# ── Database ───────────────────────────────────────────")
    lines.append(f"DATABASE_URL={config['DATABASE_URL']}")
    lines.append("")

    # Push
    lines.append("# ── Web Push Notifications (optional) ──────────────────")
    lines.append(f"VAPID_PUBLIC_KEY={config['VAPID_PUBLIC_KEY']}")
    lines.append(f"VAPID_PRIVATE_KEY={config['VAPID_PRIVATE_KEY']}")
    lines.append(f"VAPID_CLAIM_EMAIL={config['VAPID_CLAIM_EMAIL']}")
    lines.append("")

    # App
    lines.append("# ── App Settings ───────────────────────────────────────")
    lines.append(f"DEFAULT_NUM_HISTORIES={config['DEFAULT_NUM_HISTORIES']}")
    lines.append(f"DEFAULT_NUM_RESEARCH_AGENTS={config['DEFAULT_NUM_RESEARCH_AGENTS']}")
    lines.append(f"MAX_SCOPING_ROUNDS={config['MAX_SCOPING_ROUNDS']}")
    lines.append(f"MAX_QUERIES_PER_AGENT={config['MAX_QUERIES_PER_AGENT']}")
    lines.append(f"MAX_PAGES_PER_QUERY={config['MAX_PAGES_PER_QUERY']}")
    lines.append(f"MAX_CHARS_PER_PAGE={config['MAX_CHARS_PER_PAGE']}")
    lines.append(f"MAX_RESEARCH_TOKENS={config['MAX_RESEARCH_TOKENS']}")
    lines.append(f"RESEARCH_TIMEOUT_SECONDS={config['RESEARCH_TIMEOUT_SECONDS']}")
    lines.append("")

    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"\n  ✅ Configuration written to {ENV_FILE}")


# ── LLM validation ──────────────────────────────────────────────────────────


def validate_llm(config: dict) -> bool:
    import httpx

    print("\n  Testing LLM connection...")
    url = f"{config['LLM_BASE_URL'].rstrip('/')}/chat/completions"
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.post(
                url,
                headers={
                    "Authorization": f"Bearer {config['LLM_API_KEY']}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": config["LLM_MODEL"],
                    "messages": [{"role": "user", "content": "Say hi"}],
                    "max_tokens": 5,
                },
            )
            if resp.status_code == 200:
                print("  ✅ LLM connection successful!")
                return True
            print(f"  HTTP {resp.status_code}: {resp.text[:200]}")
            return False
    except httpx.ConnectError:
        print("  Cannot connect. Check your base URL.")
        return False
    except Exception as e:
        print(f"  Connection failed: {e}")
        return False


# ── VAPID key generation ────────────────────────────────────────────────────


def generate_vapid_keys() -> tuple[str, str]:
    """Generate VAPID key pair using cryptography."""
    from cryptography.hazmat.primitives.asymmetric.ec import generate_private_key, SECP256R1
    from cryptography.hazmat.primitives import serialization

    private_key = generate_private_key(SECP256R1())
    public_key = private_key.public_key()

    priv_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    pub_bytes = public_key.public_bytes(
        encoding=serialization.Encoding.X962,
        format=serialization.PublicFormat.UncompressedPoint,
    )

    return (
        base64.urlsafe_b64encode(pub_bytes).decode().rstrip("="),
        base64.urlsafe_b64encode(priv_bytes).decode().rstrip("="),
    )


# ── Database initialization ─────────────────────────────────────────────────


def init_database():
    print("  Creating database tables...")
    try:
        sys.path.insert(0, str(PROJECT_ROOT))
        from backend.database import init_db, engine
        from backend.services.app_config_service import get_app_config_service
        import asyncio

        asyncio.run(init_db())
        print("  Database initialized successfully")

        # Seed config into DB
        print("  Seeding default configuration into database...")
        svc = get_app_config_service()
        asyncio.run(svc.seed_defaults())
        print("  Configuration seeded successfully")
    except ImportError as e:
        print(f"  Could not import backend: {e}")
        print("  Run 'uv run python backend/migrations/run.py' manually.")
    except Exception as e:
        print(f"  Database init failed: {e}")


# ── Interactive wizard ──────────────────────────────────────────────────────


def wizard_interactive():
    config = dict(DEFAULTS)
    banner()

    # ── 1. LLM ──
    section("1. LLM Provider Configuration")
    print("  Any OpenAI-compatible API works (OpenAI, OpenRouter, nan.builders, etc.)\n")

    config["LLM_BASE_URL"] = prompt_input("  Base URL", DEFAULTS["LLM_BASE_URL"])
    config["LLM_API_KEY"] = prompt_input("  API Key")
    if not config["LLM_API_KEY"]:
        print("  Warning: no API key — the app won't generate histories.")
        if not prompt_bool("  Continue anyway?", default=True):
            print("  Aborted.")
            sys.exit(1)

    # Model
    print()
    for i, m in enumerate(LLM_MODELS, 1):
        tag = "  (default)" if m == DEFAULTS["LLM_MODEL"] else ""
        print(f"  [{i}] {m}{tag}")
    print("  [7] custom\n")
    while True:
        choice = input(f"  Model (1-7) [1]: ").strip() or "1"
        if choice == "7":
            config["LLM_MODEL"] = prompt_input("  Model name", "")
            break
        if choice.isdigit() and 1 <= int(choice) <= len(LLM_MODELS):
            config["LLM_MODEL"] = LLM_MODELS[int(choice) - 1]
            break

    # Test
    if config["LLM_API_KEY"]:
        if not validate_llm(config):
            prompt_bool("  Retry?", default=False)

    # ── 2. Search ──
    section("2. Web Search Configuration")
    print("  DuckDuckGo is free and requires no API key.\n")
    config["SEARCH_PROVIDER"] = prompt_choice("  Provider", SEARCH_PROVIDERS)

    if config["SEARCH_PROVIDER"] == "tavily":
        config["TAVILY_API_KEY"] = prompt_input("  Tavily API Key")
    elif config["SEARCH_PROVIDER"] == "serpapi":
        config["SERPAPI_API_KEY"] = prompt_input("  SerpAPI Key")
    elif config["SEARCH_PROVIDER"] == "hermes":
        config["HERMES_PATH"] = prompt_input("  Hermes path", DEFAULTS["HERMES_PATH"])

    # ── 3. Database ──
    section("3. Database Configuration")
    print("  SQLite — no external DB needed.\n")
    config["DATABASE_URL"] = prompt_input("  Database URL", DEFAULTS["DATABASE_URL"])

    # ── 4. Push notifications ──
    section("4. Web Push Notifications (optional)")
    print("  Alerts users when histories are ready. Can be added later.\n")
    if prompt_bool("  Generate VAPID keys now?", default=False):
        try:
            pub, priv = generate_vapid_keys()
            config["VAPID_PUBLIC_KEY"] = pub
            config["VAPID_PRIVATE_KEY"] = priv
            print("  VAPID keys generated")
        except Exception as e:
            print(f"  VAPID generation failed: {e}")
    config["VAPID_CLAIM_EMAIL"] = prompt_input(
        "  Claim email", DEFAULTS["VAPID_CLAIM_EMAIL"]
    )

    # ── 5. App settings ──
    section("5. App Settings")
    config["DEFAULT_NUM_HISTORIES"] = prompt_input(
        "  Histories per topic", DEFAULTS["DEFAULT_NUM_HISTORIES"]
    )
    config["DEFAULT_NUM_RESEARCH_AGENTS"] = prompt_input(
        "  Parallel research agents", DEFAULTS["DEFAULT_NUM_RESEARCH_AGENTS"]
    )
    config["MAX_SCOPING_ROUNDS"] = prompt_input(
        "  Max scoping rounds", DEFAULTS["MAX_SCOPING_ROUNDS"]
    )
    config["MAX_QUERIES_PER_AGENT"] = prompt_input(
        "  Max queries per agent", DEFAULTS["MAX_QUERIES_PER_AGENT"]
    )
    config["MAX_PAGES_PER_QUERY"] = prompt_input(
        "  Max pages per query", DEFAULTS["MAX_PAGES_PER_QUERY"]
    )

    # ── 6. Summary ──
    section("6. Summary")
    print()
    print(f"    Model:        {config['LLM_MODEL']}")
    print(f"    Base URL:     {config['LLM_BASE_URL']}")
    api = config["LLM_API_KEY"]
    print(f"    API Key:      {'***' + api[-4:] if api else '(not set)'}")
    print(f"    Search:       {config['SEARCH_PROVIDER']}")
    print(f"    Database:     {config['DATABASE_URL']}")
    print(f"    Push:         {'configured' if config['VAPID_PUBLIC_KEY'] else 'skipped'}")
    print()

    if prompt_bool("  Write .env file?", default=True):
        write_env(config)

    # ── 7. DB init ──
    section("7. Initialize Database")
    init_database()

    # Done
    print()
    print("╔══════════════════════════════════════════════════════════╗")
    print("║  Setup complete!                                        ║")
    print("║                                                        ║")
    print("║  Start:   bash scripts/run.sh                          ║")
    print("║  Or:      uvicorn backend.main:app --port 8080         ║")
    print("║                                                        ║")
    print("║  Open:    http://localhost:8080                         ║")
    print("╚══════════════════════════════════════════════════════════╝")
    print()


# ── Quick mode ──────────────────────────────────────────────────────────────


def wizard_quick():
    banner()
    print("  Quick mode — writing defaults to .env...\n")
    write_env(dict(DEFAULTS))
    print("\n  You MUST set LLM_API_KEY in .env before running.")
    print("  Then: bash scripts/run.sh\n")


# ── Entry point ─────────────────────────────────────────────────────────────


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "--quick":
        wizard_quick()
    else:
        wizard_interactive()


if __name__ == "__main__":
    main()